"""database

Revision ID: 00edc593b4d4
Revises: 
Create Date: 2023-04-24 16:25:45.576177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00edc593b4d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('from_spotify', sa.Boolean(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('ms_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listen_end_time'), ['end_time'], unique=False)

    op.create_table('track_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(length=120), nullable=True),
    sa.Column('track_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='fk_artist_id'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='fk_track_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_artist')
    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listen_end_time'))

    op.drop_table('listen')
    op.drop_table('user')
    op.drop_table('track')
    op.drop_table('artist')
    # ### end Alembic commands ###
