"""removed FK constraint on listen

Revision ID: f2fe5d4f3e48
Revises: ce6f7d47ccf0
Create Date: 2023-04-20 20:38:35.674697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fe5d4f3e48'
down_revision = 'ce6f7d47ccf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listen', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'track', ['track_id'], ['id'])

    # ### end Alembic commands ###
